In [ ]:
import numpy as np

# 2. Numpy exercises (26-39)

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
z3= np.intersect1d(Z1,Z2)
print(z3)

[1 4 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-19-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

False.

```np.lib.scimath.sqrt(-1)```

1j

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07','2016-08',
              dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
((A+B)*(-A/2))

array([-1.5, -1.5, -1.5])

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
Answer = np.ones(3)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=Answer)
# (1+2)*(-0.5) = -1.5
Answer

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
A=np.random.random(10)*10//1
A

array([8., 6., 5., 1., 5., 9., 9., 0., 2., 0.])

In [ ]:
B = np.random.random(10)*10
B = B - B%1
B

array([3., 5., 1., 4., 4., 2., 7., 4., 9., 0.])

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.random.randint(0,4,25).reshape(5,5)
print(Z)

[[2 1 2 3 0]
 [1 3 1 1 3]
 [0 2 0 1 1]
 [2 2 1 1 1]
 [0 1 3 1 0]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
a=np.random.randint(1,10,10)
print(a)
b=np.sort(a)
print(b)

[8 2 7 6 2 2 5 1 8 9]
[1 2 2 2 5 6 7 8 8 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
A=np.random.random((10,2))
print(A)
X,Y = A[:,0], A[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)
array = np.array(R)
R = array.reshape(10,1)
array1 = np.array(T)
T = array1.reshape(10,1)
arr = np.concatenate([R, T], axis=1)
arr

[[0.1193748  0.44068576]
 [0.98634272 0.97921316]
 [0.94231299 0.88708653]
 [0.72228618 0.85806944]
 [0.14276136 0.27549284]
 [0.27566708 0.45828904]
 [0.10695109 0.57428393]
 [0.63231057 0.58873735]
 [0.52724151 0.1618516 ]
 [0.40617959 0.2438877 ]]
[0.45656793 1.38986704 1.29417011 1.12159729 0.31028553 0.53480949
 0.584158   0.86396084 0.55152475 0.47377534]
[1.30626057 0.78177093 0.75521903 0.8711071  1.09269219 1.02926464
 1.38667184 0.74972819 0.29784636 0.54074518]


array([[0.45656793, 1.30626057],
       [1.38986704, 0.78177093],
       [1.29417011, 0.75521903],
       [1.12159729, 0.8711071 ],
       [0.31028553, 1.09269219],
       [0.53480949, 1.02926464],
       [0.584158  , 1.38667184],
       [0.86396084, 0.74972819],
       [0.55152475, 0.29784636],
       [0.47377534, 0.54074518]])

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
z = np.random.random(10)
print(max(z))
z[z.argmax()] = 0
print(max(z))

0.8243994139235026
0.8173232510653419


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
x=(Z-v)*(Z-v)
x=sqrt(x)
print(x.argmin())
print(v)
Z[x.argmin()]


78
77.62374712761687


78

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
a = np.arange(9).reshape(3,3)
for index, x in np.ndenumerate(a):
  print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 4. 0.]
 [0. 0. 4.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:, 0].argsort()])

[[8 1 1]
 [1 8 3]
 [2 8 7]]
[[1 8 3]
 [2 8 7]
 [8 1 1]]


In [ ]:
# column 2
print(Z)
print(Z[Z[:, 1].argsort()])

[[8 1 1]
 [1 8 3]
 [2 8 7]]
[[8 1 1]
 [1 8 3]
 [2 8 7]]


In [ ]:
# column 3
print(Z)
print(Z[Z[:, 2].argsort()])

[[8 1 1]
 [1 8 3]
 [2 8 7]]
[[8 1 1]
 [1 8 3]
 [2 8 7]]
