https://cafe.naver.com/esaa2019?iframe_url_utf8=%2FArticleRead.nhn%253Fclubid%3D29858915%2526page%3D1%2526menuid%3D80%2526boardtype%3DL%2526articleid%3D2286%2526referrerAllArticles%3Dfalse

기한 : 9월 8일 (금) 18시 30분

과제 : 파이썬 머신러닝 완벽 가이드 p. 1 ~ 38 필사하여 깃허브에 업로드한 뒤, 깃허브 링크를 댓글로 달아주세요.

- 책 p. 7 ~ 12 부분은 생략하시고, 구글 코랩으로 사용하셔도 됩니다.

- 개념 내용 필사(마크다운)하실 때, 1. 머신러닝의 개념, 2. 파이썬 머신러닝 생태계를 구성하는 주요 패키지 단원은 제외하셔도 됩니다.

# 03 Numpy

## 3.1 넘파이 ndarray 개요: shape, ndim


*  ndarray: numpy의 기반 데이터 타입. 이를 이용해 넘파이에서 다차원 배열을 쉽게 생성, 다양한 연산 수행 가능
*   numpy `array()` 함수: 리스트와 같은 다양한 인자를 입력 받아 ndarray로 변환
*   shape 변수: ndarray의 차원과 크기를 튜플 형태로 나타내줌

In [2]:
import numpy as np

In [8]:
array1 = np.array([1,2,3])
print(array1)
print(type(array1))
print(array1.shape)
print(array1.ndim)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1


In [9]:
array2 = np.array([[1,2,3],
                   [2,3,4]])
print(array2)
print(type(array2))
print(array2.shape)
print(array2.ndim)

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
(2, 3)
2


In [10]:
array3 = np.array([[1,2,3]])
# note that this is a matrix (2dim) while array1 is a vector(1dim, list)
print(array3)
print(type(array3))
print(array3.shape)
print(array3.ndim)

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)
2


## 3.2 ndarray의 데이터 타입: dtype, astype


ndarray내의 데이터 타입은 숫자, 문자열, 불 모두 가능

숫자형:
* int형 (8, 16, 32 bit)
* unsigned int형 (8, 16, 32 bit)
* float형 (8, 16, 32, 64, 128 bit)

여러 데이터 타입이 섞여 있을 경우 그 중 큰 데이터 타입으로 변환,통일된다.\
데이터 타입 변경은 astype()로 할 수 있다. 보통 데이터 타입 변경은 메모리를 더 절약할 때 이용됨.\
 (i.e. int형으로 충분한 경우인데 float로 되어있을 때는 int형으로 바꿔서 메모리 절약)

In [11]:
list1 = [1,2,3]
list2 = [1,2,'three']
list3 = [1,2,3.0]

In [12]:
array1 = np.array(list1)
array2 = np.array(list2)
array3 = np.array(list3)
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)

[1 2 3] int64
['1' '2' 'three'] <U21
[1. 2. 3.] float64


In [13]:
array4 = np.array([1.24, 2.33, 3.56])
print(array4, array4.dtype)

[1.24 2.33 3.56] float64


In [16]:
array4_asint = array4.astype('int16')
print(array4_asint, array4_asint.dtype) # autocorrected into int

[1 2 3] int16


## 3.3 ndarray를 편리하게 생성하기 - arange, zeros, ones


*   arange(stop) - array를 range()로 표현: 0부터 (stop값-1)까지의 값을 순차적으로 ndarray의 데이터값으로 변환
*   zeros(shape) - 튜플형태의 shape값을 입력하면 해당 shape를 가진, 모든 값을 0으로 채운 ndarray를 반환 (함수 인자로 dtype를 따로 정해주지 않으면 default로 float64형의 데이터)
*



In [2]:
arange_array = np.arange(11)
print(arange_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
zero_array = np.zeros((3,2))
print(zero_array, zero_array.dtype)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array, zero_array.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]] float64
[[0 0]
 [0 0]
 [0 0]] int32


## 3.4 ndarray의 차원과 크리를 변경하는 reshape()

남은 인자로 -1를 사용하면 알아서 알맞은 shape로 변환해줌\
`tolist()`: ndarray를 리스트 자료형으로 변환 (시각적으로 더 이해하기 쉬울 수 있는 경우)

In [7]:
starting_array = np.arange(10)
print(starting_array)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
reshape1 = starting_array.reshape(2,5)
print(reshape1)
reshape2 = starting_array.reshape(5,-1)
print(reshape2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)
print(array3d.tolist())

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [17]:
# 3차원 -> 2차원
array2 = array3d.reshape(2,-1)
print(array2)

[[0 1 2 3]
 [4 5 6 7]]


## 3.5 numpy의 ndarray의 데이터 세트 선택하기 - indexing


1.   단일값 추출
2.   슬라이싱
3.   Fancy indexing
4.   Boolean indexing



In [19]:
array1 = np.arange(1,10)
print(array1)

[1 2 3 4 5 6 7 8 9]


### 단일값 추출

인덱스는 0부터 시작, -1는 맨 뒤, -2는 맨 뒤에서 두번째

In [21]:
print(array1[2])
print(array1[-1])

3
9


In [23]:
array1[0] = 99
print(array1)

[99  2  3  4  5  6  7  8  9]


In [25]:
array2 = array1.reshape(3,3)
print(array2)
print(array2[0,0]) # first row, first column
print(array2[-1,0]) # last row, first column
print(array2[2,1]) # third row, second column

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
99
7
8


### 슬라이싱 ':'

In [28]:
array1 = np.arange(1,10)
print(array1)
print(array1[0:3]) # from 0th to (3-1)th index
print(array1[5:]) # from 5th to the end

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[6 7 8 9]


In [29]:
array1d = np.arange(1,26)
array2d = array1d.reshape(5,5)
print(array2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
print(array2d[0:2, 0:2]) # 0:2 of rows, 0:2 of columns

[[1 2]
 [6 7]]


In [31]:
print(array2d[0:3, 3:4]) # 0:3 of rows, 3:4 of columns -> 3 rows, 1 col

[[ 4]
 [ 9]
 [14]]


In [32]:
print(array2d[:2, 3:]) # upto row index 2, from col index 3 til the end
                       # 2 rows(0,1), 2 cols(3,4)

[[ 4  5]
 [ 9 10]]


In [38]:
# 2차원에서 뒤에 오는 인덱스를 없애면 1차원, row를 반환
print(array2d[0])

[1 2 3 4 5]
[[[1, 2], [3, 4], [5, 6], [7, 8]], [[9, 10], [11, 12], [13, 14], [15, 16]], [[17, 18], [19, 20], [21, 22], [23, 24]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
array1d = np.arange(1,25)
array3d = array1d.reshape(3,4,-1)
print(array3d.tolist())
print(array3d[1])
# 3차원에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환

[[[1, 2], [3, 4], [5, 6], [7, 8]], [[9, 10], [11, 12], [13, 14], [15, 16]], [[17, 18], [19, 20], [21, 22], [23, 24]]]
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


### Fancy Indexing

리스트나 ndarray로 인덱스 집합을 지정

In [44]:
print(array2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [45]:
print(array2d[[0,1],2]) # row 0,1 and col 2
print(array2d[[2,4], 0:2]) # row 2,3 and col 0,1

[3 8]
[[11 12]
 [21 22]]


### Boolean indexing
`ndarray[조건문]`

In [46]:
array1 = np.arange(1,10)
print(array1[array1>5])

[6 7 8 9]


In [49]:
array1>5


array([False, False, False, False, False,  True,  True,  True,  True])

In [50]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
print(array1[boolean_indexes])

[6 7 8 9]


In [51]:
# 지정된 index 값으로 데이터 조회
indexes = np.array([0,1,2,3])
print(array1[indexes])

[1 2 3 4]


## 3.6 행렬의 정렬 - sort(), argsort()

1.   `np.sort()` : 행렬 정렬
2.   `np.argsort(ndarray)` : 정렬된 행렬의 인덱스를 반환하기

### 행렬 정렬
`np.sort()` : 원래 행렬은 그대로 유지한 채 정렬된 행렬 반환\
`ndarray.sort()` : 원래 행렬 자체를 정렬한 형태로 변환하며 반환 값은 `None`\
\
기본적으로 오름차순 정렬\
내림차순: `np.sort()[::-1]`

In [54]:
original = np.array([3,1,9,6,4])
print(original)
# np.sort
sort1 = np.sort(original)
print(sort1)
# ndarray.sort()
sort2 = original.sort()
print(sort2)
print(original)

[3 1 9 6 4]
[1 3 4 6 9]
None
[1 3 4 6 9]


In [57]:
# np.sort, 내림차순
sort1 = np.sort(original)[::-1]
print(sort1)

[9 6 4 3 1]


2차원 이상의 경우 row or column wise 정렬\
`axis=0` sort each column, row-wise\
`axis=1` sort each row, column-wise

In [59]:
array2d = np.array([[3,7,4,8],
                   [2,1,9,12],
                   [9,14,10,3],
                   [5,13,6,11]])
sort0 = np.sort(array2d, axis=0)
sort1 = np.sort(array2d, axis=1)
print(sort0) #each columns are sorted (row-wise sort)
print(sort1) #each rows are sorted (column-wise sort)

[[ 2  1  4  3]
 [ 3  7  6  8]
 [ 5 13  9 11]
 [ 9 14 10 12]]
[[ 3  4  7  8]
 [ 1  2  9 12]
 [ 3  9 10 14]
 [ 5  6 11 13]]


### 정렬된 행렬의 인덱스를 반환하기

활용 예시 (데이터추출에서 많이 이용됨):\
`name = ['John', 'Mike', 'Kate']`\
`score = [78, 95, 88]`\
시험 성적순으로 학생이름을 출력하고자 한다면 `np.argsort(score)`를 이용해 반환된 인덱스를 `name` array에 fancy index로 적용해 출력할 수 있음.

In [61]:
original = np.array([8,6,9,5,7])
sort_indices = np.argsort(original)
print(sort_indices)
# 내림차순
sort_indices_desc = np.argsort(original)[::-1]
print(sort_indices_desc)

[3 1 4 0 2]
[2 0 4 1 3]


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

1.   행렬 내적(곱) `np.dot(A,B)`
2.   전치 행렬 `transpose(A)`



In [2]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

### 행렬 내적(곱) np.dot

In [3]:
dotproduct = np.dot(A,B)
print(dotproduct)

[[ 58  64]
 [139 154]]


### 전치 행렬 transpose

In [4]:
transposeA = np.transpose(A)
print(transposeA)

[[1 4]
 [2 5]
 [3 6]]
